sudo: false
dist: trusty

language: node_js

cache:
  directories:
  - node_modules
  - packages/heisenberg-scripts/node_modules
  - vendor

install: true

before_script:
  - phpenv local 7.1

script:
  - tasks/e2e.sh

matrix:
  include:
    - node_js: 8
    - node_js: 9

notifications:
  email: false
