sudo: false
dist: trusty

language: node_js

cache:
  directories:
  - node_modules
  - packages/heisenberg-scripts/node_modules
install: true

script:
  - tasks/e2e.sh
  - yarn lint

before_script:
  - yarn install
  - phpenv local 7.0

notifications:
  email: false

matrix:
  include:
    - node_js: 8
    - node_js: 9
