sudo: false
dist: trusty

language: node_js

cache:
  directories:
  - node_modules

install: true

script:
  - tasks/e2e-simple.sh

matrix:
  include:
    - node_js: 10
    - node_js: 11

notifications:
  email: false
