image: Visual Studio 2017
clone_depth: 50

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10

cache:
  - node_modules -> package-lock.js

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

build: off

test_script:
  - node --version
  - npm --version
  - bash tasks/e2e.sh
