image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9

services: mysql

clone_depth: 50

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

build: off

test_script:
  - node --version
  - npm --version
  - bash tasks/e2e.sh
