image: Visual Studio 2017
clone_depth: 50
services: mysql

environment:
  PHP_CHOCO_VERSION: 7.2
  PHP_CACHE_DIR: C:\tools\php
  MYSQL_DATABASE: wordpress_test
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9

cache:
  - '%PHP_CACHE_DIR% -> appveyor.yml'

init:
  - SET PATH=%PHP_CACHE_DIR%;%PATH%
  - SET COMPOSER_CACHE_DIR=%PHP_CACHE_DIR%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=0
  - SET ANSICON=121x90 (121x90)

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - IF EXIST %PHP_CACHE_DIR% (SET PHP=1)
  - IF %PHP%==0 cinst php -y --version %PHP_CHOCO_VERSION%  --params "/InstallDir:%PHP_CACHE_DIR%"
  - IF %PHP%==0 cinst composer -y --ia "/DEV=%PHP_CACHE_DIR%"
  - IF %PHP%==0 (composer --version) ELSE (composer self-update)
  - SET PATH=%MYSQL_PATH%\bin;%PATH%

build: off

test_script:
  - node --version
  - npm --version
  - php -v
  - bash tasks/e2e.sh
