'use strict';

module.exports = {
	extends: 'stylelint-config-recommended',
	plugins: [
		'stylelint-order',
		'stylelint-scss',
	],
	rules: {
		'at-rule-empty-line-before': [ 'always', {
			except: ['blockless-after-blockless', 'first-nested'],
			ignore: ['after-comment'],
			ignoreAtRules: ['else'],
		} ],
		'at-rule-name-case': 'lower',
		'at-rule-name-space-after': 'always-single-line',
		'at-rule-no-unknown': [ true, {
			ignoreAtRules: [
				'content',
				'each',
				'else',
				'extend',
				'for',
				'function',
				'if',
				'include',
				'mixin',
				'return',
				'warn',
			],
		} ],
		'at-rule-semicolon-newline-after': 'always',
		'at-rule-no-vendor-prefix': true,
		'at-rule-semicolon-space-before': 'never',
		'block-closing-brace-newline-after': [
			'always', {
				ignoreAtRules: [ 'if', 'else' ],
			},
		],
		'block-closing-brace-newline-before': 'always',
		'block-opening-brace-newline-after': 'always',
		'block-opening-brace-space-after': 'always-single-line',
		'block-opening-brace-space-before': 'always',
		'color-hex-case': 'lower',
		'color-hex-length': 'short',
		'color-named': 'never',
		'comment-empty-line-before': [ 'always', {
			ignore: ['stylelint-commands'],
		} ],
		'declaration-bang-space-after': 'never',
		'declaration-bang-space-before': 'always',
		'declaration-block-no-duplicate-properties': [ true, {
			ignore: ['consecutive-duplicates'],
		} ],
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-semicolon-newline-after': 'always',
		'declaration-block-semicolon-newline-before': 'never-multi-line',
		'declaration-block-semicolon-space-after': 'always-single-line',
		'declaration-block-semicolon-space-before': 'never',
		'declaration-block-single-line-max-declarations': 1,
		'declaration-block-trailing-semicolon': 'always',
		'declaration-colon-newline-after': 'always-multi-line',
		'declaration-colon-space-after': 'always-single-line',
		'declaration-colon-space-before': 'never',
		'declaration-empty-line-before': 'never',
		'declaration-no-important': true,
		'declaration-property-unit-whitelist': {
			'line-height': ['px'],
		},
		'font-family-name-quotes': 'always-where-recommended',
		'font-weight-notation': [ 'numeric', {
			ignore: ['relative'],
		} ],
		'function-comma-newline-after': 'always-multi-line',
		'function-comma-space-after': 'always',
		'function-comma-space-before': 'never',
		'function-max-empty-lines': 0,
		'function-name-case': [ 'lower', {
			ignoreFunctions: ['/^DXImageTransform.Microsoft.*$/'],
		} ],
		'function-parentheses-newline-inside': 'always-multi-line',
		'function-parentheses-space-inside': 'never',
		'function-url-quotes': 'never',
		'function-whitespace-after': 'always',
		indentation: 'tab',
		'length-zero-no-unit': true,
		'max-empty-lines': 1,
		'max-line-length': [ 80, {
			ignore: 'non-comments',
			ignorePattern: ['/(https?://[0-9,a-z]*.*)|(^description\\:.+)|(^tags\\:.+)/i'],
		} ],
		'media-feature-colon-space-after': 'always',
		'media-feature-colon-space-before': 'never',
		'media-feature-name-case': 'lower',
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-parentheses-space-inside': 'always',
		'media-feature-range-operator-space-after': 'always',
		'media-feature-range-operator-space-before': 'always',
		'media-query-list-comma-newline-after': 'always-multi-line',
		'media-query-list-comma-space-after': 'always-single-line',
		'media-query-list-comma-space-before': 'never',
		'no-descending-specificity': null,
		'no-eol-whitespace': true,
		'no-missing-end-of-source-newline': true,
		'number-leading-zero': 'always',
		'number-no-trailing-zeros': true,
		'order/order': [
			[
				'custom-properties',
				'dollar-variables',
				{
					type: 'at-rule',
					name: 'extend',
				},
				{
					type: 'at-rule',
					name: 'include',
					hasBlock: false,
				},
				'declarations',
				{
					type: 'at-rule',
					name: 'include',
					hasBlock: true,
				},
				'rules',
			],
		],
		'order/properties-alphabetical-order': true,
		'property-case': 'lower',
		'property-no-vendor-prefix': true,
		'rule-empty-line-before': [ 'always', {
			ignore: ['after-comment'],
			except: ['first-nested'],
		} ],
		'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
		'scss/at-else-closing-brace-space-after': 'always-intermediate',
		'scss/at-else-empty-line-before': 'never',
		'scss/at-rule-no-unknown': true,
		'scss/at-if-closing-brace-newline-after': 'always-last-in-chain',
		'scss/at-if-closing-brace-space-after': 'always-intermediate',
		'scss/selector-no-redundant-nesting-selector': true,
		'selector-attribute-brackets-space-inside': 'never',
		'selector-attribute-operator-space-after': 'never',
		'selector-attribute-operator-space-before': 'never',
		'selector-attribute-quotes': 'always',
		'selector-class-pattern': [
			'^[a-z]+(-[a-z]+)*',
			{
				message: 'Selector should use lowercase and separate words with hyphens (selector-class-pattern)',
			},
		],
		'selector-id-pattern': [
			'^[a-z]+(-[a-z]+)*',
			{
				message: 'Selector should use lowercase and separate words with hyphens (selector-id-pattern)',
			},
		],
		'selector-combinator-space-after': 'always',
		'selector-combinator-space-before': 'always',
		'selector-descendant-combinator-no-non-space': true,
		'selector-list-comma-newline-after': 'always',
		'selector-list-comma-newline-before': 'never-multi-line',
		'selector-list-comma-space-after': 'always-single-line',
		'selector-list-comma-space-before': 'never',
		'selector-max-empty-lines': 0,
		'selector-no-vendor-prefix': true,
		'selector-pseudo-class-case': 'lower',
		'selector-pseudo-class-parentheses-space-inside': 'never',
		'selector-pseudo-element-case': 'lower',
		'selector-pseudo-element-colon-notation': 'double',
		'selector-type-case': 'lower',
		'shorthand-property-no-redundant-values': true,
		'string-quotes': 'double',
		'unit-case': 'lower',
		'value-keyword-case': 'lower',
		'value-list-comma-newline-after': 'always-multi-line',
		'value-list-comma-space-after': 'always-single-line',
		'value-list-comma-space-before': 'never',
		'value-list-max-empty-lines': 0,
		'value-no-vendor-prefix': true,
	},
};
