<?php
/**
 * Icons
 *
 * IF YOU ARE EDITING THIS FILE, THEN YOU ARE EDITING A FILE THAT GETS
 * AUTOGENERATED! DO NOT EDIT THIS FILE!
 *
 * @package {{package}}
 */

if ( ! function_exists( '{{name}}_get_icon' ) ) {
	/**
	 * Get SVG Icon
	 *
	 * @param  string $icon Icon id.
	 * @param  array  $args Arguments.
	 * @return string <svg /> markup.
	 */
	function {{name}}_get_icon( string $icon, array $args = [] ) : string {
		$defaults = [
			'classname' => '',
			'height'    => '',
			'size'      => 24,
			'width'     => '',
		];

		$args = wp_parse_args( $args, $defaults );

		$classnames = ! empty( $args['classname'] ) ? 'icon ' . $args['classname'] : 'icon';
		$height     = ! empty( $args['height'] ) ? $args['height'] : $args['size'];
		$width      = ! empty( $args['width'] ) ? $args['width'] : $args['size'];
		$svg        = '';

		switch ( $icon ) {
			default:
				$svg = sprintf( 'Missing icon - %s', esc_html( $icon ) );
				break;
